# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.define "terraform" do |terraform|
    terraform.vm.hostname = "terraform"
    terraform.vm.provision "shell", 
      path: "https://raw.githubusercontent.com/automodule/bash/main/install_terraform.sh"
  end

end
